CREATE DATABASE banco_a5;

CREATE TABLE usuarios (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL,
    email VARCHAR (100) NOT NULL,
    senha VARCHAR (50) NOT NULL
);

CREATE TABLE adm (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL,
    senha VARCHAR(50) NOT NULL
);

CREATE TABLE produtos (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL,
    preco DOUBLE NOT NULL,
    formula VARCHAR(10) NOT NULL,
    quantidade INT NOT NULL
);

INSERT INTO `adm`(`id`, `nome`, `senha`) VALUES ( 1, "admin", 123 );